#!/bin/sh

memcachedb \
	-p ${MEMCACHEDB_TCP_PORT:-21201} \
	-U ${MEMCACHEDB_UDP_PORT:-21201} \
	-u ${PUSER} \
	-c ${MEMCACHEDB_CONN_LIMIT:-1024} \
	-b ${MEMCACHEDB_FAST_MALLOC_SIZE:-512} \
	$(test "${MEMCACHEDB_VERBOSE}" = 1 && echo -v) \
	$(test "${MEMCACHEDB_VERBOSE}" = 2 && echo -vv) \
	-t ${MEMCACHEDB_THREADS:-4} \
	-m ${MEMCACHEDB_CACHE_SIZE:-64} \
	-A ${MEMCACHEDB_PAGE_SIZE:-4096} \
	-f ${MEMCACHEDB_DB_FILE:-default.db} \
	-H ${MEMCACHEDB_DB_HOME:-/var/lib/memcachedb} \
	-B ${MEMCACHEDB_DB_TYPE:-btree} \
	-L ${MEMCACHEDB_LOG_BUFFER_SIZE:-32} \
	-C ${MEMCACHEDB_CHECKPOINT_INTERVAL:-300} \
	-T ${MEMCACHEDB_MEMP_TRICKLE_INTERVAL:-30} \
	-e ${MEMCACHEDB_CLEAN_CACHE_PAGES:-60} \
	-D ${MEMCACHEDB_DEADLOCK_DETECTION_INTERVAL:-100} \
	$(test "${MEMCACHEDB_DB_TNX_NOSYNC}" = 1 && echo -N)
